cc_library(
    name = "intcode",
    srcs = ["intcode.cc"],
    hdrs = ["intcode.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_google_glog//:glog",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
    ],
)
